### ISSUE TITLE
Quelques suggestions de correction

### ISSUE THREAD

**Issue by Cwpute** [nxengine/lang_french#2]
Bonjoir 👋
Je me fais un plaisir de jouer à Cave Story NX, pour la première foi, et quel kiff. Je suis sur la version flatpak dispo sur le FlatHub, ça marche presque nikel.
Ceci-dit j'ai repéré quelques traductions moyennes voire erreurs qui pouvaient être améliorées:

- [x] Toutes les fois où le mot "œuf" apparaît, le jeu affiche "Suf" voire "Sur". C'est peut-être un problème de police d'écriture… dans ce cas il serait peut-être plus sage de remplacer tous les "Œ" par des "OE"
- [x] "Il va **utilsier** ces fleurs sur Toroko ?" petite faute de frappe
- [x] Plusieurs fois dans la traduction, le mot "frénésie" est utilisé à tort ("Mimiga frénésie" et "Tonoko frénésie"), sans doute pour traduire "frenzy" - nottamment dans cette phrase: "As-tu déjà vu un Mimiga frénésie ?". La phrase est incorrecte, mal compréhensible. Elle pourait être remplacée par "As-tu déjà vu un Mimiga enragé ?" (comme dans la phrase suivante du même personnage), ou bien "[…] un Mimiga en furie ?" si l'on veut un autre mot, ou encore "As-tu déjà vu la fureur d'un Mimiga ?" pour garder la syntaxe originelle de la phrase.
- [x] "La minute où j'ai essayé de voler […]" est une translitération de l'anglais. Utiliser l'expression "Au moment-même où" ou "À l'instant où" serait plus français.
- [x] "On dirait que la chance se détourne de moi […]" une autre translitération: "On dirait que la chance me tourne le dos", "On dirait que la chance est contre moi" ou une autre expression du genre serait plus juste

Je n'ai pas encore terminé le jeu, mais j'espère bientôt en atteindre la fin ;) merci déjà pour ce beau travail de traduction, qui a déjà su faire passer les émotions du jeu original!

PS: pour cette traduction et les autres, ainsi que de potentielles prochaines autres, avez-vous pensez à utiliser Weblate ?
Pour les futures traductions de CaveStory NX

**Comment by jmfergeau** [comment]
Je ne peux pas faire grand chose étant donné que tu te bases pas sur la version **NX-evo** mais sur la version NX de [ce dépot](https://gitlab.com/coringao/cavestory-nx) qui n'est pas supportée, pas mise à jour et a probablement la majorité des fautes détectées déjà corrigées ici.

Commence déjà par jouer à la version du présent dépôt et on en reparle :)

(Par contre c'est pas normal que la nx qui est plus à jour soit dans les flatpak et pas la nx-evo. Je vais parler de ça au dev. Merci.)

**Comment by Cwpute** [comment]
Entendu 👍 je ne savais pas.
Sais-tu si je peux facilement transférer ma save de l'un vers l'autre ?

Le 22 avril 2024 12:14:15 GMT+02:00, JM Fergeau ***@***.***> a écrit :

**Comment by jmfergeau** [comment]
Dur à dire. Ça dépend si le système de save a changé entre nx et nx-evo. Faudrait tester en récupérant les fichiers de save du flatpak et je ne sais pas où ils sont enregistrés :man_shrugging:

**Comment by Cwpute** [comment]
Je viens de vérifier dans le code du repo, et les deux premiers points étaient bien corrigés. Les 3 autres cependants sont encore présents :)

**Comment by jmfergeau** [comment]
Tu sais, c'est opensource donc tu peux même faire les corrections toi-même et proposer une PR :D

**Comment by Cwpute** [comment]
C'est mon premier push to master de toute ma vie 🥹

**Comment by jmfergeau** [comment]
faut un début à tout ^^
